## Install NumPy

In [1]:
# pip install numpy

## Import NumPy

In [2]:
import numpy as np


## Introduction to NumPy
•	NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays
## What is an Array in Python?
•	An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together.

## Why Use NumPy?
* In Python we have lists that serve the purpose of arrays, but they are slow to process.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
* Arrays are very frequently used in data science, where speed and resources are very important.
## Why is NumPy Faster Than Lists?
* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
* This behaviour is called locality of reference in computer science.
* This is the main reason why NumPy is faster than lists. Also, it is optimized to work with latest CPU architectures.
* No need for data type checking.
* Item wise computations available.

## Create numpy ndarray object

### 0 dimensional array
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [3]:
arr=np.array(34)

In [4]:
arr

array(34)

### One dimensional array
* An array that has 0-D arrays as its elements is called Uni-dimensional or 1-D array.

In [5]:
one_d= np.array([1,2,3,4])

In [6]:
one_d

array([1, 2, 3, 4])

### Two dimensional array
* An array that has 1-D arrays as its elements is called a 2-D array.

In [7]:
two_d=np.array([
    [1,2,3],
    [3,4,5]
])

In [8]:
two_d

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
# 4 x 4
four=np.array([
    [1,2,3,4],
    [3,4,5,6],
    [6,7,8,9],
    [2,4,6,8]
])

In [10]:
four

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [6, 7, 8, 9],
       [2, 4, 6, 8]])

In [11]:
# 3 x 4
three_four=np.array([
    [1,3,5],
    [7,9,11],
    [2,4,6],
    [8,10,12]
])

In [12]:
three_four

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

### Checking type

In [13]:
# checking type
type(three_four)

numpy.ndarray

### Three dimensional array
* An array that has 2-D arrays as its elements is called a 3-D array.

In [14]:
three_d=np.array([[
    [1,2,3],
    [2,3,4],
    [4,5,6]
]])

In [15]:
three_d

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [16]:
thrred=np.array([
    [[1,2,3],[5,6,7]],
    
    [[1,3,6],[7,8,9]],
    
    [[1,4,8],[3,6,9]]
])

In [17]:
thrred

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 3, 6],
        [7, 8, 9]],

       [[1, 4, 8],
        [3, 6, 9]]])

### Checking Dimension

In [18]:
## Checking dimension
thrred.ndim

3

In [19]:
thrred.shape

(3, 2, 3)

In [20]:
thrred.size

18

In [21]:
thrred.dtype

dtype('int32')

In [22]:
th=np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[2,4,6,8,10],[1,3,5,7,9]],
    [[1,2,4,5,6],[0,9,8,7,6]]
])

In [23]:
th

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 2,  4,  6,  8, 10],
        [ 1,  3,  5,  7,  9]],

       [[ 1,  2,  4,  5,  6],
        [ 0,  9,  8,  7,  6]]])

In [24]:
th.shape

(3, 2, 5)

In [25]:
th.ndim

3

In [26]:
th.size

30

## Accessing an elemnt in an array

In [27]:
# one dimension
one_d


array([1, 2, 3, 4])

In [28]:
one_d[2]

3

In [29]:
# two dimension
two_d

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
two_d[0,2]

3

In [31]:
two_d[1,1]

4

In [32]:
# three dimension
thrred

array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 3, 6],
        [7, 8, 9]],

       [[1, 4, 8],
        [3, 6, 9]]])

In [33]:
thrred[1,1,2]

9

### Day 1 Works

In [34]:
# zero dimension array
zero=np.array(12)

In [35]:
zero

array(12)

In [36]:
type(zero)

numpy.ndarray

In [37]:
zero.ndim

0

In [38]:
zero.shape

()

In [39]:
zero.size

1

In [40]:
# one dimension
one=np.array(['A','B','C','D'])

In [41]:
one

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [42]:
one.ndim

1

In [43]:
one.shape

(4,)

In [44]:
one.size

4

In [45]:
# two dimension
two=np.array([
    ['A','B','C','D'],
    ['E','F','G','H'],
    ['I','J','K','L']
])

In [46]:
two

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'J', 'K', 'L']], dtype='<U1')

In [47]:
two.ndim

2

In [48]:
two.shape

(3, 4)

In [49]:
two.size

12

In [50]:
# three dimension
three=np.array([
    [['A','B','C'],['D','E','F'],['G','H','I']],
    [['J','K','L'],['M','N','O'],['P','Q','R']],
    [['S','T','U'],['V','W','X'],['X','Y','Z']]
])
    

In [51]:
three

array([[['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']],

       [['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'R']],

       [['S', 'T', 'U'],
        ['V', 'W', 'X'],
        ['X', 'Y', 'Z']]], dtype='<U1')

In [52]:
three.ndim

3

In [53]:
three.shape

(3, 3, 3)

In [54]:
three.size

27

In [55]:
# Accessing element 'Q'
three[1,2,1]

'Q'

In [56]:
four_two_three=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,24,25]]
])

In [57]:
four_two_three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 24, 25]]])

In [58]:
four_two_three.shape

(4, 2, 3)

In [59]:
# Accessing element - 20
four_two_three[3,0,1]

20

In [60]:
arr=np.array([
    [[1,2,3,4],[3,4,5,6]],
    [[11,12,13,14],[15,16,17,18]]
])

In [61]:
arr

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [62]:
# accessing element 5
arr[0,1,2]

5

## Negative slicing

In [63]:
one=np.array([1,2,3,4])
one

array([1, 2, 3, 4])

In [64]:
one[-1]

4

In [65]:
two=np.array([[1,2,3,4],[5,6,7,8]])
two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
two[-1,-1]
# two[1,-1]
# two[-1,3]

8

In [67]:
two[1,-4]
# two[-1,-4]
# two[-1,0]

5

In [68]:
# 2 x 4
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
arr1.shape

(2, 4)

In [70]:
arr1[-1,-2]

7

## Slicing arrays

In [71]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
arr1[0,1:]

array([2, 3, 4])

In [73]:
# 3x 6
arr2=np.array([[1,2,3,4,5,6],
               [3,4,5,6,7,8],
               [1,2,4,5,6,7]])
arr2

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8],
       [1, 2, 4, 5, 6, 7]])

In [74]:
arr2.shape

(3, 6)

In [75]:
arr2[:,2:5]

array([[3, 4, 5],
       [5, 6, 7],
       [4, 5, 6]])

In [76]:
arr3=np.array([
    [[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]],
    [[25,26,27,28,29,30],[31,32,33,34,35,36],[37,38,39,40,41,42],[43,44,45,46,47,48]]])
arr3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]]])

In [77]:
arr3.shape

(2, 4, 6)

In [78]:
arr3[0,:,0:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [79]:
one

array([1, 2, 3, 4])

In [80]:
one[::2]

array([1, 3])

In [81]:
arrr=np.array([1,2,3,4,5,6,7,8,9])
arrr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arrr[3:6]

array([4, 5, 6])

In [83]:
arr2

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8],
       [1, 2, 4, 5, 6, 7]])

In [84]:
arr2[:,::2]

array([[1, 3, 5],
       [3, 5, 7],
       [1, 4, 6]])

In [85]:
thsix=np.array([[1,2,3,4,5,6],
          [7,8,9,10,11,12],
          [13,14,15,16,17,18]])
thsix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [86]:
thsix[:,::3]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [87]:
thsix[:,2::3]

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [88]:
thsix[:,1::3]

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [89]:
# 4 x 6
fix=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
fix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [90]:
fix.shape

(4, 6)

In [91]:
fix[1:,::3]

array([[ 7, 10],
       [13, 16],
       [19, 22]])

# Data Types in Python
By default Python have these data types:
* strings - used to represent text data, the text is given under quote marks. Eg: "ABCD"
* integer - used to represent integer numbers. Eg: -1, -2, -3
* float - used to represent real numbers. Eg: 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. Eg: 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.
* i - integer
* b - boolean
* u - unsigned integer (i.e., zero and positive integers).astype(np.uint32)
* f - float
* c - complex float(Real+ imaginary part)
* m - timedelta 
( The timedelta class in Python is part of the datetime module and represents the difference between two dates, times, or datetime objects. It is useful for performing arithmetic with date and time objects, such as adding or subtracting time intervals.)
* M - datetime
* O - object- (object data type is a general-purpose type that can hold any kind of data. It is often used in libraries like NumPy to handle heterogeneous data, such as arrays containing elements of different types or ragged arrays where sub-arrays have different lengths.)
* S - string
* U - unicode string

	In Python 3.x and modern programming environments, strings are Unicode by default. This means that when you define a string in Python, it can contain characters from any language or symbol set supported by Unicode.

	Strings in these contexts can only represent characters from a limited set, often limited to the ASCII character set (128 characters).

	Unicode strings, on the other hand, are designed to handle text from all writing systems around the world.


## Creating Arrays With a Defined Data Type

* We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements


In [92]:
arr1=np.array([1,2,3,4])

In [93]:
arr1

array([1, 2, 3, 4])

In [94]:
arr1.dtype

dtype('int32')

In [95]:
# Convert datatype to string
arr1=np.array([1,2,3,4],dtype='S')
arr1.dtype

dtype('S1')

In [96]:
# Covert to float
arr1=np.array([1,2,3,4],dtype='f')
arr1.dtype

dtype('float32')

## Converting Data Type on Existing Arrays
* The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
* The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
* The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.


In [97]:
new=np.array([1,2.3,4,5.6,8,9.8])
print(new)
newarr=new.astype('i')
print(newarr)
print(newarr.dtype)

[1.  2.3 4.  5.6 8.  9.8]
[1 2 4 5 8 9]
int32


## The Difference Between Copy and View
* The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


## Copy

In [98]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [99]:
print(x)
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]


In [100]:
arr[0]=42

In [101]:
print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [102]:
n1=np.array([10,9,8,7,6,5])

In [103]:
n1[1]=32
y=arr.copy()

In [104]:
print(arr)
print(y)

[42  2  3  4  5]
[42  2  3  4  5]


## View

In [105]:
a=np.array([1,2,3,4,5,6])

In [106]:
print(a)

[1 2 3 4 5 6]


In [107]:
v=a.view()

In [108]:
print(v)

[1 2 3 4 5 6]


In [109]:
a[0]=42

In [110]:
print(a)
print(v)

[42  2  3  4  5  6]
[42  2  3  4  5  6]


In [111]:
v[2]=56

In [112]:
print(v)
print(a)

[42  2 56  4  5  6]
[42  2 56  4  5  6]


## Check if Array Owns its Data
* As mentioned above, copies own the data, and views does not own the data, but how can we check this?
* Every NumPy array has the attribute base that returns None if the array owns the data.
* Otherwise, the base  attribute refers to the original object.


In [113]:
s=np.array([1,2,3,4,5,6,7,8])

In [114]:
x=s.copy()
y=s.view()

In [115]:
print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7 8]


* The copy returns None.
* The view returns the original array.


## Shape of an Array
* The shape of an array is the number of elements in each dimension.
* NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [116]:
# Create 3 x 2 matrix
q=np.array([
    [1,2],[6,7],
    [4,5]
])
           
q

array([[1, 2],
       [6, 7],
       [4, 5]])

In [117]:
q.shape

(3, 2)

In [118]:
four=np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7],[2,4,6,8]])
four

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7],
       [2, 4, 6, 8]])

In [119]:
four.shape

(4, 4)

## Check Dimension 

In [120]:
four.ndim

2

## Reshaping arrays
* Reshaping means changing the shape of an array.
* The shape of an array is the number of elements in each dimension.
* By reshaping we can add or remove dimensions or change number of elements in each dimension.
* Convert the following 1-D array with 12 elements into a 2-D array.
* The outermost dimension will have 4 arrays, each with 3 elements


In [121]:
four=np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7],[2,4,6,8]],ndmin=5)
four

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8],
          [1, 3, 5, 7],
          [2, 4, 6, 8]]]]])

In [122]:
four.ndim

5

In [123]:
four.shape

(1, 1, 1, 4, 4)

In [124]:
# 2  x 3 x 5
two_three_five=np.array([
    [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
    [[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]]
])
two_three_five

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [125]:
two_three_five.shape

(2, 3, 5)

In [126]:
two_three_five.ndim

3

In [127]:
two_three_five.size

30

In [128]:
oned=np.array([1,2,3,4,5,6,7,88,9,10])
oned

array([ 1,  2,  3,  4,  5,  6,  7, 88,  9, 10])

In [129]:
newarr=oned.reshape(5,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 88]
 [ 9 10]]


In [130]:
newarr1=oned.reshape(2,1,5)
print(newarr1)

[[[ 1  2  3  4  5]]

 [[ 6  7 88  9 10]]]


In [131]:
newarr1.base

array([ 1,  2,  3,  4,  5,  6,  7, 88,  9, 10])

In [132]:
onedi=np.array([1,2,3,4])
onedi

array([1, 2, 3, 4])

In [133]:
onedi=np.array([1,2,3,4],ndmin=6)
onedi

array([[[[[[1, 2, 3, 4]]]]]])

## Flattening the arrays

•	Flattening array means converting a multidimensional array into a 1D array.
    
•	We can use reshape(-1) to do this.
    


In [134]:
flt=two_three_five.reshape(-1)
flt

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Other functions that commonly used for array creation

## 1.	Arange():
•	numpy.arange: Create an array with a range of values.


In [135]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [136]:
arr1=np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [137]:
arr2=np.arange(0,10,3)
arr2

array([0, 3, 6, 9])

In [138]:
arr3=np.arange(0,50)
arr3_reshape=arr3.reshape(10,5)
arr3_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

## 2.	Ones() :
•	The numpy.ones function is used to create an array filled with ones. You can specify the shape and data type of the array.



In [139]:
ar=np.ones(5,dtype='i')
ar

array([1, 1, 1, 1, 1], dtype=int32)

In [140]:
arr4=np.ones((3,4),dtype=int)
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [141]:
arr5=np.ones((2,3,3),dtype='i')
arr5

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

#### Default is float

In [142]:
arr6=np.ones((2,2,3))
arr6

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## 3.	Zeros():
•	The numpy.zeros function is used to create an array filled with zeros. Similar to numpy.ones, you can specify the shape and data type of the array.


In [143]:
arr7=np.zeros((2,3),dtype='i')
arr7

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [144]:
arr8=np.zeros((2,3,4))
arr8

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [145]:
arr9=np.zeros(4,dtype='i')
arr9

array([0, 0, 0, 0], dtype=int32)

## 4.	Linspace():
•	numpy.linspace: Create an array with linearly spaced values.


In [146]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [147]:
arr1=np.linspace(0,50,5)
arr1

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [148]:
arr2=np.linspace(1,10,2)
arr2

array([ 1., 10.])

## 5.	diag():
•	The numpy.diag function is used to extract or construct a diagonal array.


In [149]:
arr2=np.diag([2,4,6,8])
arr2

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

## 6.	eye():
•	numpy.eye: Create a 2-D array with ones on the diagonal and zeros elsewhere.


In [150]:
arr3=np.eye(3,dtype='i')
arr3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

# Mathematical Operations

##  1) numpy.add: 

Add two arrays element-wise.

In [151]:
arange=np.arange(20,35)
reshape=arange.reshape(3,5)
reshape

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [152]:
ss=np.arange(0,15)
ss

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
adding=np.add(arange,ss)
adding

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

##  2) numpy.subtract: 

Subtract one array from another element-wise.

In [154]:
substract=np.subtract(arange,ss)
substract

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

##  3) numpy.multiply: 

Multiply two arrays element-wise.

In [155]:
multiply=np.multiply(arange,ss)
multiply

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476])

##  4) numpy.dot: 

Dot product of two arrays.

In [156]:
dot=np.dot(arange,ss)
dot

3115

##  5) numpy.sum: 

Sum of array elements.

In [157]:
sum=np.sum(arange)
sum

405

##  6) numpy.mean: 

Mean of array elements

In [158]:
mean=np.mean(arange)
mean

27.0

##  7) numpy.std: 

Standard deviation of array elements.

In [159]:
std=np.std(arange)
std

4.320493798938574

##  8) Variance (np.var): 

Calculates the variance of the elements in the array.

In [160]:
variance=np.var(arange)
variance

18.666666666666668

##  9) numpy.max: 

Maximum value in an array.

In [161]:
max=np.max(arange)
max

34

##  10) numpy.min: 

Minimum value in an array.

In [162]:
minimum=np.min(arange)
minimum

20

In [163]:
arr=np.linspace(0,100,8)
arr

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [164]:
arr_re=arr.reshape(4,2)
arr_re

array([[  0.        ,  14.28571429],
       [ 28.57142857,  42.85714286],
       [ 57.14285714,  71.42857143],
       [ 85.71428571, 100.        ]])

In [165]:
flatten=arr_re.reshape(-1)
flatten

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [166]:
flatten_sum=np.sum(flatten)
flatten_sum

400.00000000000006

In [167]:
flatten_max=np.max(flatten)
flatten_max

100.0

In [168]:
flatten_min=np.min(flatten)
flatten_min

0.0

In [169]:
flatten_mean=np.mean(flatten)
flatten_mean

50.00000000000001

In [170]:
flatten_std=np.std(flatten)
flatten_std

32.732683535398856

In [171]:
flatten_var=np.var(flatten)
flatten_var

1071.4285714285716

In [172]:
arr=np.arange(0,18)
three=arr.reshape(2,3,3)
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [173]:
one=three.reshape(-1)
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [174]:
one.shape

(18,)

In [175]:
one.size

18

In [176]:
mean=np.mean(one)
mean

8.5

In [177]:
sum=np.sum(one)
sum

153

In [178]:
std=np.std(one)
std

5.188127472091127

In [179]:
var=np.var(one)
var

26.916666666666668

In [180]:
max=np.max(one)
max

17

In [181]:
min=np.min(one)
min

0

# Iterating Arrays
* Iterating means going through elements one by one.
* As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
* If we iterate on a 1-D array it will go through each element one by one.


## 1 -D

In [182]:
one=np.arange(0,18)
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [183]:
for i in one:
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## 2 - D

In [184]:
two=np.array([[1,2,3],[4,5,6]])
two

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
for i in two:
    for x in i:
        print(x)

1
2
3
4
5
6


## 3 - D

In [186]:
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [187]:
for i in three:
    for x in i:
        for y in x:
            print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


## Iterating Arrays Using nditer()
* The function nditer() is a helping function that can be used from very basic to very advanced iterations.
* It solves some basic issues which we face in iteration


In [188]:
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [189]:
for i in np.nditer(three):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [190]:
arr=np.array([['A','B'],['C','D'],['E','F']])
arr

array([['A', 'B'],
       ['C', 'D'],
       ['E', 'F']], dtype='<U1')

In [191]:
for x in np.nditer(arr):
    print(x)

A
B
C
D
E
F


## Enumerated Iteration Using ndenumerate()
* Enumeration means mentioning sequence number of somethings one by one.
* Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those use cases.


In [192]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [193]:
for idi,i in np.ndenumerate(arr):
    print(idi,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [194]:
two

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
for idx,x in np.ndenumerate(two):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# Joining NumPy Arrays
* Joining means putting contents of two or more arrays in a single array. You're joining them along an existing dimension (length of the table)
* We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.


### 1 - D

In [196]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1,arr2)

[1 2 3] [4 5 6]


In [197]:
array=np.concatenate((arr1,arr2))
array

array([1, 2, 3, 4, 5, 6])

### Join two 2-D arrays along rows (axis=1)

In [198]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(f'arr1={arr1}\narr2={arr2}')

arr1=[[1 2 3]
 [4 5 6]]
arr2=[[ 7  8  9]
 [10 11 12]]


In [199]:
arr=np.concatenate((arr1,arr2),axis=1)
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [200]:
arr1=np.concatenate((arr1,arr2),axis=0)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [201]:
three1=np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,17,18]]])
three2=np.array([[[18,17,16],[15,14,13],[12,11,10]],
                 [[9,8,7],[6,5,4],[3,2,1]]])
print(f'three1={three1}\nthree2={three2}')

three1=[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
three2=[[[18 17 16]
  [15 14 13]
  [12 11 10]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]


In [202]:
new_join_array=np.concatenate((three1,three2),axis=1)
new_join_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [203]:
new_join_array_axis0=np.concatenate((three1,three2),axis=0)
new_join_array_axis0

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

# Joining Arrays Using Stack Functions
* Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
* Unlike the concatenate() function, the stack() function joins 1D arrays to be one 2D array and joins 2D arrays to be one 3D array.
* We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
* We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.


### CHOOSING BETWEEN STACK AND CONCATENATION: 
The choice depends on your desired outcome:
* If you want to combine arrays with a new level of organization, use stack.
* If you simply want to join arrays along an existing dimension, use concatenate. 


In [204]:
arr1=np.array([1,2,3])
arr2=np.array([11,12,13])
arr=np.stack((arr1,arr2),axis=0)
arr

array([[ 1,  2,  3],
       [11, 12, 13]])

In [205]:
arr3=np.array([1,2,3])
arr4=np.array([11,12,13])
ar=np.stack((arr3,arr4),axis=1)
ar

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

## hstack

In [206]:
arr=np.hstack((arr1,arr2))
arr

array([ 1,  2,  3, 11, 12, 13])

In [207]:
two1=np.array([[1,3,5],[2,4,6]])
two2=np.array([[7,9,11],[8,10,12]])
print(f'two1={two1}\ntwo2={two2}')

two1=[[1 3 5]
 [2 4 6]]
two2=[[ 7  9 11]
 [ 8 10 12]]


In [208]:
new=np.hstack((two1,two2))
new
              

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

### Creating 3 x 4 x 3 matrix

In [209]:
three_four_three=np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18],[19,20,21],[22,23,24]],
    [[25,26,27],[28,29,30],[31,32,33],[34,35,36]]
])
three_four_three

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [210]:
three_four_three.shape

(3, 4, 3)

### Access centre dimension

In [211]:
three_four_three[1,::]

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [212]:
# other Methods
# three_four_three[1]
# three_four_three[1:2]

### Access centre dimension with first and middle one row wise

In [213]:
three_four_three[1,::2]

array([[13, 14, 15],
       [19, 20, 21]])

### Access centre dimension with first and last one column wise

In [214]:
three_four_three[1,:,::2]

array([[13, 15],
       [16, 18],
       [19, 21],
       [22, 24]])

### Access centre dimension with first and last column with element wise, 

In [215]:
three_four_three[1,::2,::2]

array([[13, 15],
       [19, 21]])

### Access each two dimensions last 2 rows

In [216]:
three_four_three[:,2:]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[31, 32, 33],
        [34, 35, 36]]])

### Access the middle 2 dimension middle column

In [217]:
three_four_three[1,:,1:2]

array([[14],
       [17],
       [20],
       [23]])

### Convert two dimension into 6 dimension

In [218]:
two=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],ndmin=6)
two

array([[[[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
           [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]]]]])

### Print the elements in array 'two'

In [219]:
for i in np.nditer(two):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


### Print the elements in array 'two' with index

In [220]:
for i,idi in np.ndenumerate(two):
    print(i,idi)

(0, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 0, 2) 3
(0, 0, 0, 0, 0, 3) 4
(0, 0, 0, 0, 0, 4) 5
(0, 0, 0, 0, 0, 5) 6
(0, 0, 0, 0, 0, 6) 7
(0, 0, 0, 0, 0, 7) 8
(0, 0, 0, 0, 0, 8) 9
(0, 0, 0, 0, 0, 9) 10
(0, 0, 0, 0, 1, 0) 11
(0, 0, 0, 0, 1, 1) 12
(0, 0, 0, 0, 1, 2) 13
(0, 0, 0, 0, 1, 3) 14
(0, 0, 0, 0, 1, 4) 15
(0, 0, 0, 0, 1, 5) 16
(0, 0, 0, 0, 1, 6) 17
(0, 0, 0, 0, 1, 7) 18
(0, 0, 0, 0, 1, 8) 19
(0, 0, 0, 0, 1, 9) 20


### Operations

In [221]:
np.mean(two)

10.5

In [222]:
np.std(two)

5.766281297335398

In [223]:
np.sum(two)

210

In [224]:
np.max(two)

20

In [225]:
np.min(two)

1

In [226]:
np.var(two)

33.25

In [227]:
two=np.array([[1,2,3],[4,5,6]])
two1=np.array([[11,12,13],[14,15,16]])
print('two =',two)
print('two1 =',two1)

two = [[1 2 3]
 [4 5 6]]
two1 = [[11 12 13]
 [14 15 16]]


# Splitting NumPy Arrays
•	Splitting is reverse operation of Joining.

•	Joining merges multiple arrays into one and Splitting breaks one array into multiple.

•	We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

•	If the array has less elements than required, it will adjust from the end accordingly.


In [228]:
one=np.array([1,2,3,4,5,6])
one

array([1, 2, 3, 4, 5, 6])

In [229]:
new=np.array_split(one,3)
new

[array([1, 2]), array([3, 4]), array([5, 6])]

In [230]:
new1=np.array_split(one,2)
new1

[array([1, 2, 3]), array([4, 5, 6])]

In [231]:
new2=np.array_split(one,5)
new2

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [232]:
eight=np.array([1,2,3,4,5,6,7,8])
eight

array([1, 2, 3, 4, 5, 6, 7, 8])

In [233]:
new3=np.array_split(eight,3)
new3

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [234]:
two=np.array([[1,2,3,4],[4,5,6,8],[8,9,7,6]])
two

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [8, 9, 7, 6]])

In [235]:
new4=np.array_split(two,2)
new4

[array([[1, 2, 3, 4],
        [4, 5, 6, 8]]),
 array([[8, 9, 7, 6]])]

In [236]:
new5=np.array_split(two,2,axis=1)
new5

[array([[1, 2],
        [4, 5],
        [8, 9]]),
 array([[3, 4],
        [6, 8],
        [7, 6]])]

## We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [238]:
# split=np.split(one,5)
# split

In [239]:
split1=np.split(one,3)
split1

[array([1, 2]), array([3, 4]), array([5, 6])]

# Searching Arrays
•	You can search an array for a certain value, and return the indexes that get a match.
    
•	To search an array, use the where() method.

•	For replacing a value in a array using where()

•	np.where(condition, x, y)

•	condition: An array-like structure that contains boolean values (True or False).

•	x: The values to place in the output array where the condition is True.

•	y: The values to place in the output array where the condition is False.


In [240]:
arr=np.array([1,2,3,4,5,6,3,4,4])
x=np.where(arr==4)
print(x)

(array([3, 7, 8], dtype=int64),)


In [241]:
odd=np.where(arr%2!=0)
print(odd)

(array([0, 2, 4, 6], dtype=int64),)


In [242]:
even=np.where(arr%2==0)
print(even)

(array([1, 3, 5, 7, 8], dtype=int64),)


#### Replace the elements in a list where value less than 5 with zero

In [243]:
list=np.array([1,2,3,4,5,10,11,12,13,14])
list

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [244]:
less=np.where(list<5,0,list)
less

array([ 0,  0,  0,  0,  5, 10, 11, 12, 13, 14])

#### Replace the elements in a list where value greater than 5 with 10

In [245]:
list1=np.array([1,23,35,67,43,22,11,2,3])
list1

array([ 1, 23, 35, 67, 43, 22, 11,  2,  3])

In [246]:
gr=np.where(list1>=5,10,list1)
gr

array([ 1, 10, 10, 10, 10, 10, 10,  2,  3])

In [247]:
aa=np.arange(1,13)
aa2=aa.reshape(3,4)
aa2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [248]:
a=np.where(aa2==3)
a

(array([0], dtype=int64), array([2], dtype=int64))

In [249]:
s=np.where(aa2%3==0,aa2+1,aa2)
s

array([[ 1,  2,  4,  4],
       [ 5,  7,  7,  8],
       [10, 10, 11, 13]])

In [250]:
x=np.where(aa2<3,aa2*-1,aa2)
x

array([[-1, -2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Sorting Arrays
•	Sorting means putting elements in an ordered sequence.
    
•	Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

•	The NumPy ndarray object has a function called sort(), that will sort a specified array.


In [251]:
aaaa=np.array([1,4,2,5,3])
print(np.sort(aaaa))

[1 2 3 4 5]


In [252]:
a2=np.array([[1,5,8,2,4],[2,4,6,3,8]])
print(np.sort(a2))

[[1 2 4 5 8]
 [2 3 4 6 8]]


In [253]:
a2

array([[1, 5, 8, 2, 4],
       [2, 4, 6, 3, 8]])

In [254]:
print(np.sort(aaaa)[::-1])

[5 4 3 2 1]


In [255]:
-np.sort(-aaaa)

array([5, 4, 3, 2, 1])

In [256]:
-np.sort(-a2)

array([[8, 5, 4, 2, 1],
       [8, 6, 4, 3, 2]])

In [257]:
print(np.sort(a2)[::-1,::-1])

[[8 6 4 3 2]
 [8 5 4 2 1]]


# Search Sorted (Optional)
•	There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

•	The searchsorted() method is assumed to be used on sorted arrays.

•	The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.


In [258]:
aaaa=np.array([1,4,2,5,3])
aa=np.sort(aaaa)

In [259]:
aa

array([1, 2, 3, 4, 5])

In [260]:
x=np.searchsorted(aa,3)
x

2

In [261]:
x1=np.searchsorted(aa,4,side='right')
x1

4

In [262]:
x2=np.searchsorted(aa,4,side='left')
x2

3

# Filtering Arrays
•	Getting some elements out of an existing array and creating a new array out of them is called filtering.

•	In NumPy, you filter an array using a boolean index list.
    
•	A boolean index list is a list of booleans corresponding to indexes in the array.

•	If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.


In [263]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [264]:
arr=np.arange(1,15)
filter_array=[]
for i in arr:
    if i%2==0:
        filter_array.append(True)
    else:
        filter_array.append(False)
newarr=arr[filter_array]
print(newarr)
        

[ 2  4  6  8 10 12 14]


In [265]:
arr=np.arange(1,10)
filter_arr=arr%2!=0
newarr=arr[filter_arr]
newarr

array([1, 3, 5, 7, 9])

# Random Numbers
* Random numbers are numbers that are generated in such a way that each number has an equal probability of being chosen within a specified range.
* Random Numbers are used in a wide range of applications, from scientific simulations to cryptography (including key generation, encryption, digital signatures, and secure communication protocols) and gaming
  
	- Random Events (The locations and times at which enemies appear can be controlled by random numbers to keep gameplay unpredictable and engaging)
	- Randomized Outcomes (Shuffling a deck of cards in digital card games relies on random numbers to ensure fair play and unpredictability)

* However, not all random numbers are created equal. They can be broadly categorized into two types:
  
 	1. pseudo-random numbers 
 	2. True random numbers
     
## True Random Numbers
True Random Numbers are generated from physical processes that are inherently unpredictable, like radioactive decay or atmospheric noise.

* Unpredictable: Their next value can't be guessed.
* Examples: Flipping a coin, rolling a dice, measuring radioactive decay.
  
## Pseudo-Random Numbers
Pseudo-Random Numbers are generated using algorithms and a starting value called a seed. They appear random, but are actually predictable if you know the seed.

* Deterministic: If you start with the same seed, you get the same sequence of numbers.
* Examples: Random numbers generated by computer algorithms like the Linear Congruential Generator (LCG).

	True Random Numbers: Best for cryptographic applications because they are truly unpredictable.

	Pseudo-Random Numbers: Suitable for non-cryptographic applications where high speed and reproducibility are important.

## Random Number Generation in NumPy
* Python defines a set of functions that are used to generate or manipulate random numbers through the random module. 
* Functions in the random module rely on a pseudo-random number generator function random(), which generates a random float number between 0.0 and 1.0.
* This particular type of functions is used in a lot of games, lotteries, or any application requiring a random number generation.


## Basic Random Number Generation

### 1.	Single Random Float

In [272]:
random_float=np.random.rand(5)
random_float

array([0.70281002, 0.00504351, 0.98173019, 0.95597163, 0.64107869])

### 2.	Array of Random Integers:

In [278]:
rand_integer=np.random.randint(1,10)
rand_integer

2

In [270]:
rand_int=np.random.randint(1,10,5)
rand_int

array([4, 9, 6, 9, 7])

## Random Arrays

### 1.	2D Array of Random Floats:

In [273]:
rand_float_arr=np.random.rand(3,3)
rand_float_arr

array([[0.48046416, 0.56381964, 0.41267381],
       [0.50363012, 0.40084707, 0.65983965],
       [0.60828647, 0.72434542, 0.101717  ]])

In [274]:
rand_3d=np.random.rand(3,2,5)
rand_3d

array([[[0.01884629, 0.49784902, 0.88632899, 0.90912939, 0.05204489],
        [0.09307672, 0.21896814, 0.95091209, 0.03190433, 0.08390253]],

       [[0.96610254, 0.00776557, 0.71183084, 0.24947503, 0.3265234 ],
        [0.3065212 , 0.91195189, 0.73353618, 0.37749399, 0.3073933 ]],

       [[0.97989038, 0.29787261, 0.02687896, 0.51999815, 0.96270314],
        [0.62980962, 0.16411939, 0.13212528, 0.81762661, 0.80690804]]])

### Using random.uniform

In [275]:
random_float_uniform = np.random.uniform(5, 10) 
print(random_float_uniform)



9.56267984986286


In [277]:
rand_uni_arr=np.random.uniform(5,10,10)
rand_uni_arr

array([5.7482576 , 6.15429934, 5.14492616, 5.31163939, 7.54791862,
       6.51951508, 5.80659548, 5.47047244, 7.13306959, 6.08775346])

### 2.	1D Array from Normal Distribution

In [279]:
normal=np.random.randn(10)
normal

array([ 0.37354213, -0.55740442, -1.12895039,  0.53810297,  0.05429791,
        0.23240568,  1.29868108,  2.54680827, -1.04328518, -1.43965032])

In [280]:
normal_2d=np.random.randn(4,3)
normal_2d

array([[-0.57425701, -2.03406875,  0.36972528],
       [ 1.1654539 ,  1.10672671, -0.05682602],
       [ 0.65712305, -0.25230563, -0.56199941],
       [-0.05349215, -0.98792651, -1.65709572]])

In [283]:
normal_3d=np.random.randn(3,2,5)
normal_3d

array([[[ 0.46435614,  0.78497087,  0.27605395,  0.48205932,
          0.14983394],
        [ 1.30897087,  1.13163785,  1.00346333, -1.50104712,
         -1.16253506]],

       [[ 0.84675804,  0.58026568, -1.7993318 , -1.79560043,
         -1.17693169],
        [ 0.86959468,  1.23376273, -1.13071366,  1.48740946,
          0.95380482]],

       [[ 1.24722985,  0.79186642, -0.15577061, -0.42431098,
          0.99944916],
        [ 0.44791701, -0.4111723 ,  1.10629003, -0.03578806,
         -0.9741583 ]]])

## Random Choice

### 1.	Without Replacement:

In [284]:
rand_choice=np.random.choice([10,20,30,40,50],size=2,replace=False)
rand_choice

array([40, 20])

In [285]:
rand_choice=np.random.choice([10,20,30,40,50],size=2,replace=False)
rand_choice

array([30, 40])

In [286]:
rand_choice=np.random.choice([10,20,30,40,50],size=2,replace=False)
rand_choice

array([50, 10])

### 2.	With Replacement:

In [287]:
choice_with=np.random.choice([10,20,30,40,50],size=2,replace=True)
choice_with

array([30, 40])

In [288]:
choice_with=np.random.choice([10,20,30,40,50],size=2,replace=True)
choice_with

array([40, 40])

In [289]:
choice_with=np.random.choice([10,20,30,40,50],size=2,replace=True)
choice_with

array([20, 30])

## Setting a Seed
	Setting a seed ensures reproducibility of random number sequences


In [290]:
np.random.seed(42)
reproducible_random_array = np.random.rand(5)
print(reproducible_random_array)  


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [293]:
np.random.seed(42)
reproducible_random_array = np.random.randint(10,20,5)
print(reproducible_random_array)  


[16 13 17 14 16]


## Shuffling

### 1.	Shuffle Array Elements

In [297]:
array=np.array([1,2,3,4,5])
np.random.shuffle(array)
print(array)

[5 4 1 2 3]


### 2.	Shuffle Rows of a 2D Array

In [298]:
array_2d=np.array([[1,2],[3,4],[5,6]])
np.random.shuffle(array_2d)
print(array_2d)

[[1 2]
 [5 6]
 [3 4]]
