In [2]:
import numpy as np

## 1.	Explain the difference between deep copy and shallow copy in NumPy arrays.

### deep copy
* deep copy is a copy where the any changes in the original does not change in copy.
### shallow copy
* shallow copy is a copy where the changes in original change in the copy.

## 2.	Explain the difference between array and list?

### list
* a list contain different types of data types.
* list have huge memory usage
### array
* array contain same data type
* less memory usage
* stored in contigenously location
* item wise computetion is possible

## 3.	Given an array a = np.array([10, 20, 30]), how do you square every element in the array?

In [6]:
a=np.array([10,20,30])
square=np.square(a)
square

array([100, 400, 900])

## 4.	How do you create an array of zeros with shape (3, 4)?

In [5]:
zeros=np.zeros((3,4),dtype=int)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 5.	Given the 1D array a = np.array([1, 2, 3, 4, 5]), how do you calculate the cumulative sum of the elements?

In [10]:
a=np.array([1,2,3,4,5])
cumulative_sum=np.sum(a)
cumulative_sum

15

## 6.	How do you reverse the elements in a NumPy array a = np.array([1, 2, 3, 4, 5])?

In [12]:
a=np.array([1,2,3,4,5])
reverse=a[::-1]
reverse

array([5, 4, 3, 2, 1])

## 7.	How do you find the indices of elements that are greater than 4 in the array a = np.array([1, 2, 3, 4, 5, 6, 7])?

In [18]:
a=np.array([1,2,3,4,5,6,7])
for idx,x in np.ndenumerate(a):
    if x>4:
        print(idx,x)

(4,) 5
(5,) 6
(6,) 7


## 8.	How do you create a 2D array with random floating-point numbers between 0 and 1 of shape (3, 3)?

In [19]:
float=np.random.rand(3,3)
float

array([[0.84532441, 0.30372642, 0.58735078],
       [0.27767741, 0.93917968, 0.6430771 ],
       [0.84701087, 0.65150951, 0.12115447]])

## 9.	Extract the elements at indices [0, 2, 4] from the array a = np.array([10, 20, 30, 40, 50]).

In [25]:
a=np.array([10,20,30,40,50])
new=a[::2]
new

array([10, 30, 50])

## 10.	Given the array a = np.array([10, 20, 30, 40]), how do you normalize the array so that its values are between 0 and 1?

In [34]:
a=np.array([10,20,30,40])
normalize=(a-np.min(a))/(np.max(a)-np.min(a))
normalize

array([0.        , 0.33333333, 0.66666667, 1.        ])

## 11.	How do you concatenate two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) along the first axis?

In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
new=np.concatenate((a,b),axis=0)
new

array([1, 2, 3, 4, 5, 6])

## 12.	How do you find the dot product of two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])?

In [36]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
new=np.dot(a,b)
new

32

## 13.	How do you create an identity matrix of size 4x4?

In [38]:
one=np.ones((4,4),dtype=int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 14.	How do you generate an array with random integers between 1 and 100, of shape (4, 4)?

In [41]:
random_int=np.random.randint(1,100,(4,4))
random_int

array([[16, 23, 48, 99],
       [51, 96, 20, 22],
       [ 8, 84, 20, 57],
       [ 1, 51, 10, 39]])

## 15.	How do you split a NumPy array a = np.array([1, 2, 3, 4, 5, 6]) into three sub-arrays?

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
split=np.array_split(a,3)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

## 16.	Given the 2D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how do you compute the sum of all elements along the second axis?

In [49]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new=np.sum(a,axis=1)
new

array([ 6, 15, 24])

## 17.	How do you compute the element-wise maximum of two arrays a = np.array([1, 2, 3]) and b = np.array([3, 2, 1])?

In [52]:
a=np.array([1,2,3])
b=np.array([3,2,1])
new=np.max((a,b),axis=0)
new

array([3, 2, 3])

## 18.	How do you find the unique elements in the array a = np.array([1, 2, 2, 3, 3, 4, 5])?

In [53]:
a = np.array([1, 2, 2, 3, 3, 4, 5])
new=np.unique(a)
new

array([1, 2, 3, 4, 5])

## 19.	How do you use np.arange to create an array of values between 1 and 50 with a step of 3, and then filter the elements that are divisible by 5?

In [62]:
new=np.arange(1,50,3)
new1=new%5==0
a=new[new1]
print(a)

[10 25 40]


## 20.	Given the array a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), use np.where to replace elements in a that are less than 3 with -3, then  horizontally stack a and b.

In [71]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a=np.where(a<3,-3,a)
hstack=np.hstack((a,b))
hstack

array([-3, -3,  3,  4,  5,  6,  7,  8,  9, 10])

## 21.	How do you generate a 3D array of shape (4, 3, 2) where each 2D slice (3x2) is filled with random values between 0 and 1, and then normalize the entire 3D array to values between 0 and 1 (with respect to the min and max of the array)?

In [77]:
np.random.seed(42)
a=np.random.rand(4,3,2)
a

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848],
        [0.15601864, 0.15599452]],

       [[0.05808361, 0.86617615],
        [0.60111501, 0.70807258],
        [0.02058449, 0.96990985]],

       [[0.83244264, 0.21233911],
        [0.18182497, 0.18340451],
        [0.30424224, 0.52475643]],

       [[0.43194502, 0.29122914],
        [0.61185289, 0.13949386],
        [0.29214465, 0.36636184]]])

In [78]:
normalize=(a-np.min(a))/(np.max(a)-np.min(a))
normalize

array([[[0.37284965, 0.9797798 ],
        [0.74938422, 0.60893137],
        [0.14266357, 0.14263816]],

       [[0.03950081, 0.89072903],
        [0.61151903, 0.72418595],
        [0.        , 1.        ]],

       [[0.85519484, 0.20199041],
        [0.16984743, 0.17151129],
        [0.2987993 , 0.53108445]],

       [[0.4333188 , 0.28509156],
        [0.62283009, 0.12525671],
        [0.28605594, 0.36423482]]])

## 22.	Given a 2D array of shape (5, 5) filled with random integers between 1 and 100, replace all odd numbers with -1 and all even numbers with 1.

In [88]:
a=np.random.randint(1,100,(5,5))
a

array([[71, 44,  8, 47, 35],
       [78, 81, 36, 50,  4],
       [ 2,  6, 54,  4, 54],
       [93, 63, 18, 90, 44],
       [34, 74, 62, 14, 95]])

In [89]:
a=np.where(a%2!=0,-1,1)
a

array([[-1,  1,  1, -1, -1],
       [ 1, -1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [-1, -1,  1,  1,  1],
       [ 1,  1,  1,  1, -1]])

## 23.	Given a large 1D array of 10 million random floating-point numbers between 0 and 1, find the 10th and 90th percentile of the values.

In [92]:
a=np.random.rand(10000000)
percentile=np.percentile(a,10)
percentile

0.09993289407905184

In [93]:
percentile1=np.percentile(a,90)
percentile1

0.8999446660820476

## 24.	Given a 5x5 matrix arr, use np.where to:
•	Replace all elements greater than 10 with the value 100.

•	Replace all elements less than or equal to 10 with the value -100


In [107]:
a=np.arange(0,25)
a=a.reshape(5,5)

In [108]:
a=np.where(a<=10,-100,100)
a

array([[-100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100],
       [-100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100]])

## 25.	Given a 2D array arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), perform the following operations:
•	Horizontally split the array into two equal parts.
    
•	Vertically split the array into three equal parts.
    
•	Stack the split parts vertically and horizontally.


In [110]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [111]:
split=np.array_split(arr,2,axis=1)
split

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [112]:
ver_split=np.array_split(arr,3)
ver_split

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [113]:
stack=np.stack(split,ver_split)
stack

TypeError: 'list' object cannot be interpreted as an integer